version: '3.8'  # Явно указываем версию для совместимости

services:
  api:
    container_name: cat-pinterest-api
    build:
      context: ./api
    ports:
      - "3000:3000"  # Пробрасываем порт NestJS напрямую
    networks:
      - cat-pinterest-net
    environment:
      NODE_ENV: prod
      DATABASE_URL: "postgres://postgres:1@db:5432/support_lk_db"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: cat-pinterest-api-pg
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: support_lk_db
    volumes:
      - pg_data:/var/lib/postgresql/data  # Сохраняем данные между перезапусками
    networks:
      - cat-pinterest-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

networks:
  cat-pinterest-net:

volumes:
  pg_data:  # Объявляем volume для БД