
services:
  # Прокси (оставлен, но будет игнорироваться без фронтенда)
  proxy:
    container_name: cat-pinterest-proxy
    image: nginx:1.24-alpine-slim
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    ports:
      - "8080:80"
    networks:
      - cat-pinterest-net
    # Отключаем зависимость от API, чтобы запускался независимо
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Бэкенд (основной сервис)
  cat-pinterest-api:
    container_name: cat-pinterest-api
    build:
      context: ./api/
    ports:
      - "3000:3000"  # Добавляем прямой доступ к API
    networks:
      - cat-pinterest-net
    environment:
      NODE_ENV: prod
      DATABASE_URL: "postgres://postgres:1@cat-pinterest-api-pg:5432/support_lk_db"
    depends_on:
      cat-pinterest-api-pg:
        condition: service_healthy

  # Фронтенд (оставлен, но не будет мешать)
  cat-pinterest-front:
    container_name: cat-pinterest-front
    image: cat-pinterest-front
    build:
      context: ./front/
    networks:
      - cat-pinterest-net
    ports:
    - "5173:80"
    environment:
      NODE_ENV: prod
    # Явно отключаем автостарт
    restart: "no"
    # Добавляем healthcheck для возможного ручного запуска
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # БД (без изменений)
  cat-pinterest-api-pg:
    container_name: cat-pinterest-api-pg
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data  # Добавляем volume для сохранения данных
    networks:
      - cat-pinterest-net
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: support_lk_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ts.com  # Замените на свой email
      PGADMIN_DEFAULT_PASSWORD: admin_ts   # Замените на свой пароль
    networks:
      - cat-pinterest-net
    ports:
      - "5050:80"
    depends_on:
      - cat-pinterest-api-pg

networks:
  cat-pinterest-net:

volumes:
  pg_data:  # Объявляем volume для БД
